name: 'citibike_analytics'
version: '1.0.0'
config-version: 2

profile: 'citibike_analytics'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  citibike_analytics:
    staging:
      +materialized: view